name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run tests
      run: ./gradlew test
    - name: Check code formatting
      run: ./gradlew spotlessCheck
    - name: Create DMG package
      run: ./gradlew packageDmg
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: shiori-editor-dmg
        path: build/compose/binaries/main/dmg/*.dmg
