name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean package
    - name: Run tests
      run: mvn test
    - name: Create package
      run: mvn jpackage:jpackage
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: shiori-editor-dmg
        path: target/jpackage/Shiori Editor-1.0.0.dmg
